/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class InternalPoloDbClient {
  constructor(path: string)
  collection(name: string): InternalPoloDbCollection
}
export declare class InternalPoloDbCollection {
  insertOne(doc: string, callback: (err: null | Error, result: string) => void): void
  insertMany(docs: string[], callback: (err: null | Error, result: string) => void): void
  findOne(filter: string, callback: (err: null | Error, result: string | null) => void): void
  find(filter: string): InternalPoloDbCursor
  updateOne(filter: string, update: string, callback: (err: null | Error, result: string) => void): void
  updateMany(filter: string, update: string, callback: (err: null | Error, result: string) => void): void
  deleteOne(filter: string, callback: (err: null | Error, result: string) => void): void
  deleteMany(filter: string, callback: (err: null | Error, result: string) => void): void
}
export declare class InternalPoloDbCursor {
  skip(n: number): this
  limit(n: number): this
  sort(sortDoc: string): this
  toArray(callback: (err: null | Error, result: string) => void): void
}
